question_data = [
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Geography",
         "question": "Rhode Island is actually located on the US mainland, despite its name.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Animals", "question": "A slug&rsquo;s blood is green.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "RAM stands for Random Access Memory.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
         "question": "An average human can go two weeks without water.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Animals",
                                          "question": "The internet browser Firefox is named after the Red Panda.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
         "incorrect_answers": ["False"]}
]
